info|2021-01-26 15:12:01.744257|[INITIALIZER][initGlobalConfig],enableCompress=true,compatibilityVersion=2.7.1,versionNumber=34013440,enableStat=false,chainId=1,useSMCrypto=false
info|2021-01-26 15:12:01.751166|[INITIALIZER][SecureInitializer]loading privateKey
info|2021-01-26 15:12:01.867014|[INITIALIZER][SecureInitializer]get pub of node,nodeID=8767659a776ee7c3e1a6c16748d3c05dcbdfd27a8eab5e03f37b3bf71adb920180cd09718971e5f1598b59a2c8ff57a2a4fc05a91d9b0a55abdcca27375da9a5
info|2021-01-26 15:12:01.868760|[INITIALIZER][SecureInitializer]use user certificate,file=conf//node.crt
info|2021-01-26 15:12:01.885999|[INITIALIZER][SecureInitializer]use ca certificate,file=conf//ca.crt
info|2021-01-26 15:12:01.886154|[INITIALIZER][SecureInitializer]use ca,file=conf//
error|2021-01-26 15:12:02.634746|[INITIALIZER][P2PInitializer]initConfig for P2PInitializer failed,check Port=30301,EINFO=Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >
std::exception::what: bind: Address already in use

